Convert identifiers package to TypeScript
broadinstitute/gnomad-browser-toolkit pull request #24
Opened 2020-09-02 19:02 UTC by nawatts

2020-09-02 19:53 UTC, huy-nguyen requested changes

2020-09-02 19:53 UTC, huy-nguyen commented on packages/identifiers/package.json
> +    "build": "rm -rf lib && tsc",
For small packages like this, it's not a problem to use `tsc` to compile TypeScript code but for larger codebase, something like Rollup is better.

2020-09-02 19:53 UTC, huy-nguyen commented on packages/identifiers/tsconfig.json
> +  "include": [
Is this necessary?

2020-09-02 19:56 UTC, nawatts commented on packages/identifiers/tsconfig.json
> +  "include": [
It turns out that it is not. Will remove.

2020-09-02 20:00 UTC, nawatts commented on packages/identifiers/src/identifiers.ts
> +export const normalizeRegionId = (regionId: string): string => {
Ooh, did not know that.

2020-09-02 20:47 UTC, nawatts commented on packages/identifiers/package.json
> +    "build": "rm -rf lib && tsc",
I've been meaning to ask you about tooling. Let's discuss on Slack.

2020-09-03 18:55 UTC, huy-nguyen approved these changes

2020-09-03 19:41 UTC, merged